package by.bsuir.phoneshop.web.command;

public enum CommandName {
    LOGIN, PRODUCT_LIST, PRODUCT_DETAILS, ADD_TO_CART, CART, DELETE_CART_ITEM,
    UPDATE_CART, CHECKOUT, PLACE_ORDER, ORDER_OVERVIEW, MINICART, AUTHORISE,
    REGISTER, SIGNUP, LOGOUT, USERS, UPDATE_USERS
}